
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rexhina
 */
public class BusManagementSystem extends javax.swing.JFrame {

    /**
     * Creates new form BusManagementSystem
     */
    public BusManagementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LNametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Rolecmb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Addbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        busPannel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IDTXT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Platetxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        Addbtn1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        UpdateBtn1 = new javax.swing.JButton();
        DeleteBtn1 = new javax.swing.JButton();
        timetablePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        IDTXT2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        starttimeTxt = new javax.swing.JTextField();
        endtimetxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        Addbtn2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        UpdateBtn2 = new javax.swing.JButton();
        DeleteBtn2 = new javax.swing.JButton();
        assignemployee = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        Assignbtn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList7 = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        assignitinerrarry = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList8 = new javax.swing.JList<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList9 = new javax.swing.JList<>();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList10 = new javax.swing.JList<>();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList11 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addEmployeeMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        employeePanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                employeePanelComponentAdded(evt);
            }
        });
        employeePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                employeePanelComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Create Employee");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("LastName:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Role");

        Rolecmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Driver", "Busman" }));

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        Addbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.setEnabled(false);
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.setEnabled(false);
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeePanelLayout.createSequentialGroup()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(122, 122, 122)
                                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nametxt)
                                    .addComponent(LNametxt)
                                    .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rolecmb, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addComponent(UpdateBtn)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteBtn))
                            .addGroup(employeePanelLayout.createSequentialGroup()
                                .addComponent(Addbtn)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(280, 280, 280)))))
                .addGap(33, 33, 33))
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(IDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Nametxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(LNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(Rolecmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn)
                    .addComponent(UpdateBtn)
                    .addComponent(jButton2)
                    .addComponent(Addbtn))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        busPannel.setPreferredSize(new java.awt.Dimension(686, 407));
        busPannel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                busPannelComponentAdded(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Create Bus");

        jLabel7.setText("ID :");

        jLabel8.setText("Bus Plate:");

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jList2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        Addbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Addbtn1.setText("Add");
        Addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addbtn1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        UpdateBtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateBtn1.setText("Update");
        UpdateBtn1.setEnabled(false);
        UpdateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtn1ActionPerformed(evt);
            }
        });

        DeleteBtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteBtn1.setText("Delete");
        DeleteBtn1.setEnabled(false);
        DeleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busPannelLayout = new javax.swing.GroupLayout(busPannel);
        busPannel.setLayout(busPannelLayout);
        busPannelLayout.setHorizontalGroup(
            busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busPannelLayout.createSequentialGroup()
                .addGroup(busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(busPannelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(Addbtn1)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(UpdateBtn1)
                        .addGap(43, 43, 43)
                        .addComponent(DeleteBtn1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, busPannelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IDTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(Platetxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        busPannelLayout.setVerticalGroup(
            busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busPannelLayout.createSequentialGroup()
                .addGroup(busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(busPannelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(busPannelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6)
                        .addGap(56, 56, 56)
                        .addGroup(busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(IDTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Platetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(busPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbtn1)
                    .addComponent(jButton3)
                    .addComponent(UpdateBtn1)
                    .addComponent(DeleteBtn1))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        timetablePanel.setPreferredSize(new java.awt.Dimension(686, 407));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Itenerrary");

        jLabel10.setText("ID:");

        jLabel11.setText("Date:");

        jLabel12.setText("Start Time:");

        jLabel13.setText("End Time:");

        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jList3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList3KeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        Addbtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Addbtn2.setText("Add");
        Addbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addbtn2ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        UpdateBtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UpdateBtn2.setText("Update");
        UpdateBtn2.setEnabled(false);
        UpdateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtn2ActionPerformed(evt);
            }
        });

        DeleteBtn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteBtn2.setText("Delete");
        DeleteBtn2.setEnabled(false);
        DeleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timetablePanelLayout = new javax.swing.GroupLayout(timetablePanel);
        timetablePanel.setLayout(timetablePanelLayout);
        timetablePanelLayout.setHorizontalGroup(
            timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetablePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetablePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(timetablePanelLayout.createSequentialGroup()
                        .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(timetablePanelLayout.createSequentialGroup()
                                .addComponent(Addbtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(16, 16, 16))
                            .addComponent(datetxt)
                            .addComponent(IDTXT2)
                            .addComponent(starttimeTxt)
                            .addComponent(endtimetxt))))
                .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetablePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(timetablePanelLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(UpdateBtn2)
                        .addGap(46, 46, 46)
                        .addComponent(DeleteBtn2)
                        .addGap(0, 72, Short.MAX_VALUE))))
        );
        timetablePanelLayout.setVerticalGroup(
            timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timetablePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timetablePanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(IDTXT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(starttimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endtimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(timetablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbtn2)
                    .addComponent(jButton4)
                    .addComponent(UpdateBtn2)
                    .addComponent(DeleteBtn2))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        assignemployee.setPreferredSize(new java.awt.Dimension(686, 407));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Assign Employee");

        jList4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jList4);

        jList5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList5MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jList5);

        Assignbtn.setText("Assign");
        Assignbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignbtnActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(jList6);

        jScrollPane7.setViewportView(jList7);

        jLabel15.setText("Works On:");

        jLabel16.setText("Has Employees:");

        javax.swing.GroupLayout assignemployeeLayout = new javax.swing.GroupLayout(assignemployee);
        assignemployee.setLayout(assignemployeeLayout);
        assignemployeeLayout.setHorizontalGroup(
            assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignemployeeLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Assignbtn)
                .addGap(97, 97, 97)
                .addGroup(assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(69, 69, 69))
            .addGroup(assignemployeeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assignemployeeLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(assignemployeeLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(229, 229, 229))))
        );
        assignemployeeLayout.setVerticalGroup(
            assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignemployeeLayout.createSequentialGroup()
                .addGroup(assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assignemployeeLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(Assignbtn))
                    .addGroup(assignemployeeLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(assignemployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Assign Itinerrarry");

        jList8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList8MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jList8);

        jList9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList9MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jList9);

        jScrollPane10.setViewportView(jList10);

        jScrollPane11.setViewportView(jList11);

        jButton1.setText("Assign");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Busses:");

        jLabel19.setText("Itinerrarry:");

        javax.swing.GroupLayout assignitinerrarryLayout = new javax.swing.GroupLayout(assignitinerrarry);
        assignitinerrarry.setLayout(assignitinerrarryLayout);
        assignitinerrarryLayout.setHorizontalGroup(
            assignitinerrarryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignitinerrarryLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(assignitinerrarryLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(assignitinerrarryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assignitinerrarryLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(assignitinerrarryLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(169, 169, 169))
                    .addGroup(assignitinerrarryLayout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75))
        );
        assignitinerrarryLayout.setVerticalGroup(
            assignitinerrarryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assignitinerrarryLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addGroup(assignitinerrarryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(assignitinerrarryLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(assignitinerrarryLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(assignitinerrarryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(assignitinerrarryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(9, 9, 9)
                        .addGroup(assignitinerrarryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jMenu1.setText("Employee");

        addEmployeeMenu.setText("Create Employee");
        addEmployeeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeMenuMouseClicked(evt);
            }
        });
        addEmployeeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeMenuActionPerformed(evt);
            }
        });
        jMenu1.add(addEmployeeMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bus");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Create Bus");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu3.setText("Assign Employee");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Timetable");

        jMenuItem1.setText("Create Itinerrary");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Assign Itinerrary to Bus");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(busPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(timetablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(assignemployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 10, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(assignitinerrarry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(busPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(timetablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(assignemployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(assignitinerrarry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void addEmployeeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeMenuMouseClicked
        // TODO add your handling code here:
         employeePanel.setVisible(true);
        busPannel.setVisible(false);
        timetablePanel.setVisible(false);
        assignemployee.setVisible(false);
        assignitinerrarry.setVisible(false);
        
    }//GEN-LAST:event_addEmployeeMenuMouseClicked

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
         //Add button in employee panel
        Employee empl=new Employee();
        empl.setIdEmployee(Integer.parseInt(IDtxt.getText()));
        empl.setName(Nametxt.getText()); 
        empl.setLastName(LNametxt.getText());        
        Role r= new Role();
        String role=Rolecmb.getSelectedItem().toString();
        
        if(role.equals("Driver")) 
        {
            r.setIdRole(0);
            r.setName("Driver");
        }
        else {r.setIdRole(1); r.setName("Busman");}
        empl.setRole((r));
       
        BusManagement.getInstance().getEmployee().add(empl);
        if(ListFunctions.checkFields(Nametxt.getText(), LNametxt.getText())==false)//check if TextFields are empty
        {ListFunctions.addElementToList(jList1, empl);}

        try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        
        Statement stmt=con.createStatement();  
        
        String query = "INSERT INTO `employee` (`ID_Employee`, `Name`, `LastName`, `Id_Role`) VALUES\n" +
            "('"+empl.getIdEmployee()+"','"+Nametxt.getText()+"', '"+LNametxt.getText()+"', '"+r.getIdRole()+"')";
        stmt.execute(query);
               

        }
        catch(Exception ex){ 
            System.out.println(ex+" this went wrong");
        }  
        IDtxt.setText("");
        Nametxt.setText("");
        LNametxt.setText("");        
        Rolecmb.setSelectedIndex(0);
        Nametxt.requestFocus(true);
    }//GEN-LAST:event_AddbtnActionPerformed

    private void addEmployeeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeMenuActionPerformed
        // TODO add your handling code here:
        employeePanel.setVisible(true);
        busPannel.setVisible(false);
        timetablePanel.setVisible(false);
        assignemployee.setVisible(false);
        assignitinerrarry.setVisible(false);
        
    }//GEN-LAST:event_addEmployeeMenuActionPerformed
private void FillJList(){
     try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `employee`";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Employee empl = new Employee();
            int id= e.getInt(1);//id
            String fN = e.getString(2);
            empl.setName(fN);
            String lN = e.getString(3);
            empl.setLastName(lN);
            int idRole = e.getInt(4);
            Role role = new Role();
            if(idRole==0){role.setName("Driver"); role.setIdRole(0);}
            else {role.setName("Busman"); role.setIdRole(1);}
            empl.setRole(role);
            empl.setIdEmployee(id);
            dm.addElement(empl);
        }
        jList1.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        } 
}
     private void FillJList2(){
     try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `bus`";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Bus bus = new Bus();
            int id= e.getInt(1);//id
            String plate = e.getString(2);
            bus.setIdBus(id);
            bus.setPlate(plate);
            dm.addElement(bus);
        }
        jList2.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        } 
}
     private void FillJList3(){
     try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `timetable`";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Timetable ttable = new Timetable();
            int id= e.getInt(1);//id
            String date = e.getString(2);
            String stime = e.getString(3);
            String etime = e.getString(4);
            ttable.setID(id);
            ttable.setDate(date);
            ttable.setStartTime(stime);
            ttable.setEndTime(etime);
            dm.addElement(ttable);
        }
        jList3.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        } 
}
     private void FillJList4(){
          try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `employee`";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Employee empl = new Employee();
            int id= e.getInt(1);//id
            String fN = e.getString(2);
            empl.setName(fN);
            String lN = e.getString(3);
            empl.setLastName(lN);
            int idRole = e.getInt(4);
            Role role = new Role();
            if(idRole==0){role.setName("Driver"); role.setIdRole(0);}
            else {role.setName("Busman"); role.setIdRole(1);}
            empl.setRole(role);
            empl.setIdEmployee(id);            
            dm.addElement(empl);
        }
        jList4.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
     }
     private void FillJList5(){
         try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `bus`";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Bus bus = new Bus();
            int id= e.getInt(1);//id
            String plate = e.getString(2);
            bus.setIdBus(id);
            bus.setPlate(plate);
            dm.addElement(bus);
        }
        jList5.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        } 
     }
     private void FillJList9(){
         try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `bus`";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Bus bus = new Bus();
            int id= e.getInt(1);//id
            String plate = e.getString(2);
            bus.setIdBus(id);
            bus.setPlate(plate);
            dm.addElement(bus);
        }
        jList9.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        } 
     }
     private void FillJList8(){
         try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `timetable`";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Timetable ttable = new Timetable();
            int id= e.getInt(1);//id
            String date = e.getString(2);
            String stime = e.getString(3);
            String etime = e.getString(4);
            ttable.setID(id);
            ttable.setDate(date);
            ttable.setStartTime(stime);
            ttable.setEndTime(etime);
            dm.addElement(ttable);
        }
        jList8.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
     }
    private void employeePanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_employeePanelComponentShown
        
         FillJList();
         employeePanel.setVisible(true);
        busPannel.setVisible(false);
        timetablePanel.setVisible(false);
        assignemployee.setVisible(false);
        assignitinerrarry.setVisible(false);
    }//GEN-LAST:event_employeePanelComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Nametxt.setText("");
        IDtxt.setText("");
        IDtxt.setEnabled(true);
        LNametxt.setText("");
        Rolecmb.setSelectedIndex(0);
        Nametxt.requestFocus(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        IDtxt.setEnabled(false);
         jList1.requestFocus();
        int index= jList1.getSelectedIndex();
        if(index>=0 && index < jList1.getModel().getSize())
        {
            UpdateBtn.setEnabled(true);
            DeleteBtn.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        for(int i=0;i<jList1.getModel().getSize();i++)
        {
            dm.addElement(jList1.getModel().getElementAt(i));
        }
        
        Employee e= (Employee) dm.getElementAt(index);
        
        //populate the textFields
        Nametxt.setText(e.getName());
        LNametxt.setText(e.getLastName());
        IDtxt.setText(String.valueOf(e.getIdEmployee()));
        Rolecmb.setSelectedItem(e.getRole().getName());
    }//GEN-LAST:event_jList1MouseClicked

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
         //Update button in employee panel
         
         int index= jList1.getSelectedIndex();
        Object obj=jList1.getModel().getElementAt(index);
        Employee in = (Employee) obj; 
        Role r= new Role();
        String role=Rolecmb.getSelectedItem().toString();
        
        if(role.equals("Driver")) 
        {
            r.setIdRole(0);
            r.setName("Driver");
        }
        else {r.setIdRole(1); r.setName("Busman");}
        in.setRole((r));        
        in.setName(Nametxt.getText());
        in.setLastName(LNametxt.getText());
       
        
          try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();  
        String query = "UPDATE `employee` SET `Name`='" +
            in.getName()+"',`LastName`='"+in.getLastName()+"',`Id_Role`='"+in.getRole().getIdRole()+"' WHERE `ID_Employee`='"+in.getIdEmployee()+"'";
        stmt.execute(query);
            //System.out.println(in.getName()+" "+st.getLName());
                
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
          FillJList();
        Nametxt.setText("");
        LNametxt.setText("");
        IDtxt.setText("");
        IDtxt.setEnabled(true);
        Rolecmb.setSelectedIndex(0);
        Nametxt.requestFocus(true);
        
        UpdateBtn.setEnabled(false);
        DeleteBtn.setEnabled(false);
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
          int index= jList1.getSelectedIndex();
        Object obj=jList1.getModel().getElementAt(index);
        Employee in = (Employee) obj; 
        
        
          try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();  
        String query = "DELETE FROM `employee` WHERE`ID_Employee`='"+in.getIdEmployee()+"'";
        stmt.execute(query);
            //System.out.println(in.getName()+" "+st.getLName());
                
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
          FillJList();
        Nametxt.setText("");
        LNametxt.setText("");
        IDtxt.setText("");
        IDtxt.setEnabled(true);
        Rolecmb.setSelectedIndex(0);
        Nametxt.requestFocus(true);
        
        UpdateBtn.setEnabled(false);
        DeleteBtn.setEnabled(false);
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        busPannel.setVisible(true);
        employeePanel.setVisible(false);
        timetablePanel.setVisible(false);
        assignitinerrarry.setVisible(false);
        assignemployee.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        //KeyPress event in employee panel to select the elements from the list with up and down key
        IDtxt.setEnabled(false);
        Employee e= new Employee();
        
        if (evt.getKeyCode()==KeyEvent.VK_UP) 
        {
        int index= jList1.getSelectedIndex();
        
        if(index>=0 && index < jList1.getModel().getSize())
        {
            DeleteBtn.setEnabled(true);
            UpdateBtn.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        for(int i=0;i<jList1.getModel().getSize();i++)
        {
            dm.addElement(jList1.getModel().getElementAt(i));
        }
        if(index!=0) // if the index of the element is not 0, then continue selecting the previous student, otherwise do not do anything. 
                     //In this way we will not get an OutOfBounds exception
            e= (Employee) dm.getElementAt(index-1);
        else if(index==0)
            e= (Employee) dm.getElementAt(index);
        //populate the textFields
        IDtxt.setText(String.valueOf(e.getIdEmployee()));
        Nametxt.setText(e.getName());
        LNametxt.setText(e.getLastName());
        Rolecmb.setSelectedItem(e.getRole().getName());
        }
        
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN) 
        {
        int index= jList1.getSelectedIndex();
        
        if(index>=0 && index < jList1.getModel().getSize())
        {
            DeleteBtn.setEnabled(true);
            UpdateBtn.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        
        for(int i=0;i<jList1.getModel().getSize();i++)
        {
            dm.addElement(jList1.getModel().getElementAt(i));
        }
        if(index!=jList1.getModel().getSize()-1)// if the index of the element is not in the end of the list, then continue selecting the next student, otherwise do not do anything. 
                                                //In this way we will not get an OutOfBounds exception
            e= (Employee) dm.getElementAt(index+1);
        else if(index==jList1.getModel().getSize()-1)
            e= (Employee) dm.getElementAt(index);
        //populate the textFields
        IDtxt.setText(String.valueOf(e.getIdEmployee()));
        Nametxt.setText(e.getName());
        LNametxt.setText(e.getLastName());
        Rolecmb.setSelectedItem(e.getRole().getName());
        } 
    }//GEN-LAST:event_jList1KeyPressed

    private void Addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addbtn1ActionPerformed
        Bus bus=new Bus();
        bus.setIdBus(Integer.parseInt(IDTXT.getText()));
        bus.setPlate(Platetxt.getText());         
       
        BusManagement.getInstance().getBus().add(bus);
        if(ListFunctions.checkFields(IDTXT.getText(), Platetxt.getText())==false)//check if TextFields are empty
        {ListFunctions.addElementToList(jList2, bus);}

        try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        
        Statement stmt=con.createStatement();  
        
        String query = "INSERT INTO `bus`(`ID_Bus`, `Palate`) VALUES\n" +
            "('"+IDTXT.getText()+"','"+Platetxt.getText()+"')";
        stmt.execute(query);
               

        }
        catch(Exception ex){ 
            System.out.println(ex+" this went wrong");
        }  
        IDTXT.setText("");
        Platetxt.setText("");        
        Platetxt.requestFocus(true);
    }//GEN-LAST:event_Addbtn1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        IDTXT.setText("");
        IDTXT.setEnabled(true);
        Platetxt.setText("");        
        Platetxt.requestFocus(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void UpdateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtn1ActionPerformed
        // TODO add your handling code here:
        
         int index= jList2.getSelectedIndex();
        Object obj=jList2.getModel().getElementAt(index);
        Bus in = (Bus) obj; 
              
        in.setIdBus(Integer.parseInt(IDTXT.getText()));
        in.setPlate(Platetxt.getText());       
        
          try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();  
        String query = "UPDATE `bus` SET `Palate`='"+in.getPlate()+"' WHERE `ID_Bus`='"+in.getIdBus()+"'";
        stmt.execute(query);
            //System.out.println(in.getName()+" "+st.getLName());
                
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
          FillJList2();
        IDTXT.setText("");
        IDTXT.setEnabled(true);
        Platetxt.setText("");
        
        Platetxt.requestFocus(true);
        
        UpdateBtn1.setEnabled(false);
        DeleteBtn1.setEnabled(false);
    }//GEN-LAST:event_UpdateBtn1ActionPerformed

    private void DeleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtn1ActionPerformed
        // TODO add your handling code here:
         int index= jList2.getSelectedIndex();
        Object obj=jList2.getModel().getElementAt(index);
        Bus in = (Bus) obj; 
        
        
          try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();  
        String query = "DELETE FROM `bus` WHERE`ID_Bus`='"+in.getIdBus()+"'";
        stmt.execute(query);
            //System.out.println(in.getName()+" "+st.getLName());
                
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
          FillJList2();
        IDTXT.setText("");
        IDTXT.setEnabled(true);
        Platetxt.setText("");
        
        Platetxt.requestFocus(true);
        
        UpdateBtn1.setEnabled(false);
        DeleteBtn1.setEnabled(false);
    }//GEN-LAST:event_DeleteBtn1ActionPerformed

    private void busPannelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_busPannelComponentAdded
        // TODO add your handling code here:
        FillJList2();
    }//GEN-LAST:event_busPannelComponentAdded

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        busPannel.setVisible(true);
        employeePanel.setVisible(false);
        timetablePanel.setVisible(false);
        assignitinerrarry.setVisible(false);
        assignemployee.setVisible(false);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
        // TODO add your handling code here:
        busPannel.setVisible(true);
        employeePanel.setVisible(false);
        timetablePanel.setVisible(false);
        assignitinerrarry.setVisible(false);
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
         // TODO add your handling code here:
         IDTXT.setEnabled(false);
         jList2.requestFocus();
        int index= jList2.getSelectedIndex();
        if(index>=0 && index < jList2.getModel().getSize())
        {
            UpdateBtn1.setEnabled(true);
            DeleteBtn1.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        for(int i=0;i<jList2.getModel().getSize();i++)
        {
            dm.addElement(jList2.getModel().getElementAt(i));
        }
        
        Bus b= (Bus) dm.getElementAt(index);
        
        //populate the textFields
        IDTXT.setText(String.valueOf(b.getIdBus()));
        Platetxt.setText(b.getPlate());
        
    }//GEN-LAST:event_jList2MouseClicked

    private void jList2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList2KeyPressed
        // TODO add your handling code here:
         IDTXT.setEnabled(false);
        Bus b= new Bus();
        
        if (evt.getKeyCode()==KeyEvent.VK_UP) 
        {
        int index= jList2.getSelectedIndex();
        
        if(index>=0 && index < jList2.getModel().getSize())
        {
            DeleteBtn1.setEnabled(true);
            UpdateBtn1.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        for(int i=0;i<jList2.getModel().getSize();i++)
        {
            dm.addElement(jList2.getModel().getElementAt(i));
        }
        if(index!=0) // if the index of the element is not 0, then continue selecting the previous student, otherwise do not do anything. 
                     //In this way we will not get an OutOfBounds exception
            b= (Bus) dm.getElementAt(index-1);
        else if(index==0)
            b= (Bus) dm.getElementAt(index);
        //populate the textFields
        IDTXT.setText(String.valueOf(b.getIdBus()));
        Platetxt.setText(b.getPlate());
        
        }
        
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN) 
        {
        int index= jList2.getSelectedIndex();
        
        if(index>=0 && index < jList2.getModel().getSize())
        {
            DeleteBtn1.setEnabled(true);
            UpdateBtn1.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        
        for(int i=0;i<jList2.getModel().getSize();i++)
        {
            dm.addElement(jList2.getModel().getElementAt(i));
        }
        if(index!=jList2.getModel().getSize()-1)// if the index of the element is not in the end of the list, then continue selecting the next student, otherwise do not do anything. 
                                                //In this way we will not get an OutOfBounds exception
            b= (Bus) dm.getElementAt(index+1);
        else if(index==jList2.getModel().getSize()-1)
            b= (Bus) dm.getElementAt(index);
        //populate the textFields
        IDTXT.setText(String.valueOf(b.getIdBus()));
        Platetxt.setText(b.getPlate());
        } 
    }//GEN-LAST:event_jList2KeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        timetablePanel.setVisible(true);
        busPannel.setVisible(false);
        employeePanel.setVisible(false);
        assignemployee.setVisible(false);
        assignitinerrarry.setVisible(false);
        FillJList3();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Addbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addbtn2ActionPerformed
        // TODO add your handling code here:
         Timetable ttable=new Timetable();
        ttable.setID(Integer.parseInt(IDTXT2.getText()));
        ttable.setDate(datetxt.getText());  
        ttable.setStartTime(starttimeTxt.getText());
        ttable.setEndTime(endtimetxt.getText());
       
        BusManagement.getInstance().getTimetable().add(ttable);
        if(ListFunctions.checkFields(IDTXT2.getText(), starttimeTxt.getText())==false)//check if TextFields are empty
        {ListFunctions.addElementToList(jList3, ttable);}

        try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        
        Statement stmt=con.createStatement();  
        
        String query = "INSERT INTO `timetable`(`ID`, `Date`, `StartTime`, `EndTime`) VALUES\n" +
            "('"+IDTXT2.getText()+"','"+datetxt.getText()+"','"+starttimeTxt.getText()+"','"+endtimetxt.getText()+"')";
        stmt.execute(query);
               

        }
        catch(Exception ex){ 
            System.out.println(ex+" this went wrong");
        }  
        IDTXT2.setText("");
        datetxt.setText("");  
        starttimeTxt.setText("");
        endtimetxt.setText("");
        datetxt.requestFocus(true);
    }//GEN-LAST:event_Addbtn2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        IDTXT2.setText("");
        IDTXT2.setEnabled(true);
        datetxt.setText("");  
        starttimeTxt.setText("");
        endtimetxt.setText("");
        datetxt.requestFocus(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void UpdateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtn2ActionPerformed
        // TODO add your handling code here:
          int index= jList3.getSelectedIndex();
        Object obj=jList3.getModel().getElementAt(index);
        Timetable in = (Timetable) obj; 
              
        in.setID(Integer.parseInt(IDTXT2.getText()));
        in.setDate(datetxt.getText());
        in.setStartTime(starttimeTxt.getText());
        in.setEndTime(endtimetxt.getText());
        
        
          try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();  
        String query = "UPDATE `timetable` SET `Date`='"+in.getDate()+"',`StartTime`='"+in.getStartTime()+"',`EndTime`='"+
                in.getEndTime()+"'WHERE `ID`='"+in.getID()+"'";
        stmt.execute(query);
            
                
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
          FillJList3();
        IDTXT2.setText("");
        IDTXT2.setEnabled(true);
        datetxt.setText("");  
        starttimeTxt.setText("");
        endtimetxt.setText("");
        datetxt.requestFocus(true);
        
        UpdateBtn2.setEnabled(false);
        DeleteBtn2.setEnabled(false);
    }//GEN-LAST:event_UpdateBtn2ActionPerformed

    private void DeleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtn2ActionPerformed
        // TODO add your handling code here:
       
         int index= jList3.getSelectedIndex();
        Object obj=jList3.getModel().getElementAt(index);
        Timetable in = (Timetable) obj; 
        
        
          try{
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();  
        String query = "DELETE FROM `timetable` WHERE`ID`='"+in.getID()+"'";
        stmt.execute(query);
            //System.out.println(in.getName()+" "+st.getLName());
                
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
          FillJList3();
        IDTXT2.setText("");
        IDTXT2.setEnabled(true);
        datetxt.setText("");  
        starttimeTxt.setText("");
        endtimetxt.setText("");
        datetxt.requestFocus(true);
        
        UpdateBtn2.setEnabled(false);
        DeleteBtn2.setEnabled(false);
    }//GEN-LAST:event_DeleteBtn2ActionPerformed

    private void jList3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList3KeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:
         IDTXT2.setEnabled(false);
        Timetable t= new Timetable();
        
        if (evt.getKeyCode()==KeyEvent.VK_UP) 
        {
        int index= jList3.getSelectedIndex();
        
        if(index>=0 && index < jList3.getModel().getSize())
        {
            DeleteBtn2.setEnabled(true);
            UpdateBtn2.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        for(int i=0;i<jList3.getModel().getSize();i++)
        {
            dm.addElement(jList3.getModel().getElementAt(i));
        }
        if(index!=0) // if the index of the element is not 0, then continue selecting the previous student, otherwise do not do anything. 
                     //In this way we will not get an OutOfBounds exception
            t= (Timetable) dm.getElementAt(index-1);
        else if(index==0)
            t= (Timetable) dm.getElementAt(index);
        //populate the textFields
        IDTXT2.setText(String.valueOf(t.getID()));
        datetxt.setText(t.getDate());
        starttimeTxt.setText(t.getStartTime());
        endtimetxt.setText(t.getEndTime());
        datetxt.requestFocus();
        
        }
        
        else if(evt.getKeyCode()==KeyEvent.VK_DOWN) 
        {
        int index= jList3.getSelectedIndex();
        
        if(index>=0 && index < jList3.getModel().getSize())
        {
            DeleteBtn2.setEnabled(true);
            UpdateBtn2.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        
        for(int i=0;i<jList3.getModel().getSize();i++)
        {
            dm.addElement(jList3.getModel().getElementAt(i));
        }
        if(index!=jList3.getModel().getSize()-1)// if the index of the element is not in the end of the list, then continue selecting the next student, otherwise do not do anything. 
                                                //In this way we will not get an OutOfBounds exception
            t= (Timetable) dm.getElementAt(index+1);
        else if(index==jList3.getModel().getSize()-1)
            t= (Timetable) dm.getElementAt(index);
        //populate the textFields
        IDTXT2.setText(String.valueOf(t.getID()));
        datetxt.setText(t.getDate());
        starttimeTxt.setText(t.getStartTime());
        endtimetxt.setText(t.getEndTime());
        } 
    }//GEN-LAST:event_jList3KeyPressed

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
         IDTXT2.setEnabled(false);
         jList3.requestFocus();
        int index= jList3.getSelectedIndex();
        if(index>=0 && index < jList3.getModel().getSize())
        {
            UpdateBtn2.setEnabled(true);
            DeleteBtn2.setEnabled(true);
        }
        
        DefaultListModel dm= new DefaultListModel();
        for(int i=0;i<jList3.getModel().getSize();i++)
        {
            dm.addElement(jList3.getModel().getElementAt(i));
        }
        
        Timetable t= (Timetable) dm.getElementAt(index);
        
        //populate the textFields
        IDTXT2.setText(String.valueOf(t.getID()));       
        datetxt.setText(t.getDate());
        starttimeTxt.setText(t.getStartTime());
        endtimetxt.setText(t.getEndTime());
    }//GEN-LAST:event_jList3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       
        employeePanel.setVisible(false);
        busPannel.setVisible(false);
        timetablePanel.setVisible(false);
        assignemployee.setVisible(true);
        assignitinerrarry.setVisible(false);
        FillJList4();
        FillJList5();
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void AssignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignbtnActionPerformed
        // TODO add your handling code here:
          
        int index= jList5.getSelectedIndex();
        Object obj=jList5.getModel().getElementAt(index);
        Bus in = (Bus) obj;
        in.setEmployee(new ArrayList<> ());
        
        int[] selectedIndices = jList4.getSelectedIndices();
          try{
        //DBManager controler = DBManager.getInstance();
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        //Statement stmt = DBManager.getStatement();
        for (int i=0;i<selectedIndices.length;i++)
        {
            Object nObj = jList4.getModel().getElementAt(selectedIndices[i]);
            in.getEmployee().add((Employee)nObj);
        }
        
        Iterator iterator1 = in.getEmployee().iterator();
        while(iterator1.hasNext())
        {
            Employee e = (Employee)iterator1.next();
            Statement stmt=con.createStatement();  
        String query = "UPDATE `employee` SET `ID_Bus`='" +
            in.getIdBus()+"' WHERE `ID_Employee`='"+e.getIdEmployee()+"'";
        stmt.execute(query);
               
           
        }
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }          
    }//GEN-LAST:event_AssignbtnActionPerformed

    private void jList5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList5MouseClicked
        
         try{
        jList5.requestFocus();
        int index= jList5.getSelectedIndex();
        DefaultListModel dm1= new DefaultListModel();
        
        for(int i=0;i<jList5.getModel().getSize();i++)
        {
            dm1.addElement(jList5.getModel().getElementAt(i));
        }
        
        Bus bus= (Bus) dm1.getElementAt(index);
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `employee` WHERE ID_Bus='"+bus.getIdBus()+"'" ;
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Employee empl = new Employee();
            int id= e.getInt(1);//id
            String fN = e.getString(2);
            empl.setName(fN);
            String lN = e.getString(3);
            empl.setLastName(lN);
            int idRole = e.getInt(4);
            Role role = new Role();
            if(idRole==0){role.setName("Driver"); role.setIdRole(0);}
            else {role.setName("Busman"); role.setIdRole(1);}
            empl.setRole(role);
            empl.setIdEmployee(id);
            dm.addElement(empl);
        }
        jList7.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
    }//GEN-LAST:event_jList5MouseClicked

    private void jList4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList4MouseClicked
        try{
        jList4.requestFocus();
        int index= jList4.getSelectedIndex();
        DefaultListModel dm1= new DefaultListModel();
        
        for(int i=0;i<jList4.getModel().getSize();i++)
        {
            dm1.addElement(jList4.getModel().getElementAt(i));
        }
        Employee empl= (Employee) dm1.getElementAt(index);
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT bus.* FROM `bus` \n" +
          "inner join `employee` on bus.ID_Bus=employee.ID_Bus\n" +
           "WHERE employee.ID_Employee='"+empl.getIdEmployee()+"'";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Bus bus = new Bus();
            int id= e.getInt(1);//id
            String plate = e.getString(2);
            bus.setIdBus(id);
            bus.setPlate(plate);
            dm.addElement(bus);
        }
        jList6.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        } 
    }//GEN-LAST:event_jList4MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        employeePanel.setVisible(false);
        busPannel.setVisible(false);
        timetablePanel.setVisible(false);
        assignemployee.setVisible(false);
        assignitinerrarry.setVisible(true);
        FillJList8();
        FillJList9();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  
        int index= jList9.getSelectedIndex();
        Object obj=jList9.getModel().getElementAt(index);
        Bus in = (Bus) obj;
        in.setTimetable(new ArrayList<> ());
        
        int[] selectedIndices = jList8.getSelectedIndices();
          try{
        //DBManager controler = DBManager.getInstance();
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        //Statement stmt = DBManager.getStatement();
        for (int i=0;i<selectedIndices.length;i++)
        {
            Object nObj = jList8.getModel().getElementAt(selectedIndices[i]);
            in.getTimetable().add((Timetable)nObj);
        }
        
        Iterator iterator1 = in.getTimetable().iterator();
        while(iterator1.hasNext())
        {
            Timetable e = (Timetable)iterator1.next();
            Statement stmt=con.createStatement();  
        String query = "UPDATE `timetable` SET `ID_Bus`='" +
            in.getIdBus()+"' WHERE `ID`='"+e.getID()+"'";
        stmt.execute(query);
               
           
        }
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList9MouseClicked
        try{
        jList9.requestFocus();
        int index= jList9.getSelectedIndex();
        DefaultListModel dm1= new DefaultListModel();
        
        for(int i=0;i<jList9.getModel().getSize();i++)
        {
            dm1.addElement(jList9.getModel().getElementAt(i));
        }
        
        Bus bus= (Bus) dm1.getElementAt(index);
        
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT * FROM `timetable` WHERE ID_Bus='"+bus.getIdBus()+"'" ;
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Timetable ttable = new Timetable();
            int id= e.getInt(1);//id
            String date = e.getString(2);
            String stime = e.getString(3);
            String etime = e.getString(4);
            ttable.setID(id);
            ttable.setDate(date);
            ttable.setStartTime(stime);
            ttable.setEndTime(etime);
            dm.addElement(ttable);
        }
        jList11.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        }
    }//GEN-LAST:event_jList9MouseClicked

    private void jList8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList8MouseClicked
        try{
        jList8.requestFocus();
        int index= jList8.getSelectedIndex();
        DefaultListModel dm1= new DefaultListModel();
        
        for(int i=0;i<jList8.getModel().getSize();i++)
        {
            dm1.addElement(jList8.getModel().getElementAt(i));
        }
        Timetable ttable= (Timetable) dm1.getElementAt(index);
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/busmanagement","rexhina","test123");
        Statement stmt=con.createStatement();          
        String query = "SELECT bus.* FROM `bus` \n" +
          "inner join `timetable` on bus.ID_Bus=timetable.ID_Bus\n" +
           "WHERE timetable.ID='"+ ttable.getID()+"'";
        
        ResultSet e = stmt.executeQuery(query);
        if(e.wasNull()) return;
        DefaultListModel dm = new DefaultListModel();
        while(e.next())
        {
            Bus bus = new Bus();
            int id= e.getInt(1);//id
            String plate = e.getString(2);
            bus.setIdBus(id);
            bus.setPlate(plate);
            dm.addElement(bus);
        }
        jList10.setModel(dm);
        
        }
        catch(Exception e){ 
            System.out.println(e+" this went wrong");
        } 
    }//GEN-LAST:event_jList8MouseClicked

    private void employeePanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_employeePanelComponentAdded
        
         FillJList();
         employeePanel.setVisible(true);
        busPannel.setVisible(false);
        timetablePanel.setVisible(false);
        assignemployee.setVisible(false);
        assignitinerrarry.setVisible(false);
    }//GEN-LAST:event_employeePanelComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusManagementSystem().setVisible(true);                
            }
        });
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Addbtn1;
    private javax.swing.JButton Addbtn2;
    private javax.swing.JButton Assignbtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton DeleteBtn1;
    private javax.swing.JButton DeleteBtn2;
    private javax.swing.JTextField IDTXT;
    private javax.swing.JTextField IDTXT2;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JTextField LNametxt;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JTextField Platetxt;
    private javax.swing.JComboBox<String> Rolecmb;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton UpdateBtn1;
    private javax.swing.JButton UpdateBtn2;
    private javax.swing.JMenuItem addEmployeeMenu;
    private javax.swing.JPanel assignemployee;
    private javax.swing.JPanel assignitinerrarry;
    private javax.swing.JPanel busPannel;
    private javax.swing.JTextField datetxt;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JTextField endtimetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList10;
    private javax.swing.JList<String> jList11;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JList<String> jList6;
    private javax.swing.JList<String> jList7;
    private javax.swing.JList<String> jList8;
    private javax.swing.JList<String> jList9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField starttimeTxt;
    private javax.swing.JPanel timetablePanel;
    // End of variables declaration//GEN-END:variables
}
